name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake 3.29
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29.6'

      - name: Install LLVM/Clang 19
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lsb-release gnupg ninja-build
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo apt-get install -y clang-tools-19 llvm-19-tools lld-19

      - name: Configure CMake (Ninja generator)
        env:
          CC: clang-19
          CXX: clang++-19
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-19 -DCMAKE_CXX_COMPILER=clang++-19

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure
